/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.FleetDirectory;
import Business.Car;
import java.awt.CardLayout;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author saikumarganga
 */
public class CreateAccountJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private FleetDirectory fleetDirectory;
    String alphaNumericRegex = "^[a-zA-Z0-9]*$";
    String alphaRegex = "^[a-zA-Z]*$";
    String yearRegex = "^(19|20)\\d{2}$";

    /**
     * Creates new form CreateAccountJPanel
     */
    CreateAccountJPanel(JPanel userProcessContainer, FleetDirectory fleetDirectory) {
        initComponents();
        this.fleetDirectory = fleetDirectory;
        this.userProcessContainer = userProcessContainer;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtmanufactureType = new javax.swing.JTextField();
        txtModelNumber = new javax.swing.JTextField();
        txtSerialNumber = new javax.swing.JTextField();
        txtManufacturedYear = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        checkAvailabilityYes = new javax.swing.JCheckBox();
        checkAvailabilityNo = new javax.swing.JCheckBox();
        checkExpCertYes = new javax.swing.JCheckBox();
        checkExpCertNo = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        txtAvailableSeats = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 204));
        setForeground(new java.awt.Color(204, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setRequestFocusEnabled(false);

        lblTitle.setBackground(new java.awt.Color(255, 153, 153));
        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(51, 0, 204));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create Uber Rides");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Manufacturer Type:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Model :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Serial Number:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Manufactured Year:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("City:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Availablity Status:");

        txtmanufactureType.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtModelNumber.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtSerialNumber.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtManufacturedYear.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtCity.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("Expired Maintenance Certificate:");

        btnCreate.setBackground(new java.awt.Color(153, 153, 153));
        btnCreate.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(153, 153, 153));
        btnBack.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        buttonGroup1.add(checkAvailabilityYes);
        checkAvailabilityYes.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        checkAvailabilityYes.setText("Yes");
        checkAvailabilityYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAvailabilityYesActionPerformed(evt);
            }
        });

        buttonGroup1.add(checkAvailabilityNo);
        checkAvailabilityNo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        checkAvailabilityNo.setText("No");
        checkAvailabilityNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAvailabilityNoActionPerformed(evt);
            }
        });

        buttonGroup2.add(checkExpCertYes);
        checkExpCertYes.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        checkExpCertYes.setText("Yes");

        buttonGroup2.add(checkExpCertNo);
        checkExpCertNo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        checkExpCertNo.setText("No");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText(" Available Seats:");

        txtAvailableSeats.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBack))
                        .addComponent(txtModelNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                        .addComponent(txtSerialNumber)
                        .addComponent(txtManufacturedYear)
                        .addComponent(txtCity)
                        .addComponent(txtmanufactureType)
                        .addComponent(txtAvailableSeats, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkExpCertYes)
                        .addGap(18, 18, 18)
                        .addComponent(checkExpCertNo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkAvailabilityYes)
                        .addGap(18, 18, 18)
                        .addComponent(checkAvailabilityNo)))
                .addGap(780, 780, 780))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtmanufactureType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtModelNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(txtSerialNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtManufacturedYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtAvailableSeats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(checkAvailabilityYes)
                    .addComponent(checkAvailabilityNo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkExpCertYes)
                    .addComponent(checkExpCertNo)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnBack))
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:

        String manufactureType = txtmanufactureType.getText();
        if (manufactureType == null || manufactureType.equals("") || !manufactureType.matches(alphaNumericRegex)) {
            JOptionPane.showMessageDialog(null, "Please enter a valid manufacturer type");
            return;
        }

        String modelNumber = txtModelNumber.getText();
        if (modelNumber == null || modelNumber.equals("") || !modelNumber.matches(alphaNumericRegex)) {
            JOptionPane.showMessageDialog(null, "Please enter a valid model number");
            return;
        }

        String serialNumber = txtSerialNumber.getText();
        if (serialNumber == null || serialNumber.equals("") || !serialNumber.matches(alphaNumericRegex)) {
            JOptionPane.showMessageDialog(null, "Please enter a valid serial Number");
            return;
        }

        String manufacturedYear = txtManufacturedYear.getText();
        if (manufacturedYear == null || !manufacturedYear.matches(yearRegex)) {
            JOptionPane.showMessageDialog(null, " Please type a valid manufactured year ");
            return;
        }

        String maxSeats = txtAvailableSeats.getText();
        try {
            Integer.parseInt(maxSeats);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, " Please type a valid seat number ");
            return;
        }

        String city = txtCity.getText();
        if (city == null || city.equals("") || !city.matches(alphaRegex)) {
            JOptionPane.showMessageDialog(null, "Please enter a valid city");
            return;
        }

        if (!checkAvailabilityNo.isSelected() && !checkAvailabilityYes.isSelected()) {
            JOptionPane.showMessageDialog(null, "Please select an option for Availability Status");
            return;
        }

        if (!checkExpCertNo.isSelected() && !checkExpCertYes.isSelected()) {
            JOptionPane.showMessageDialog(null, "Please select an option for Expired Maintainence Certificate");
            return;
        }

        if (checkAvailabilityNo.isSelected()) {
            checkAvailabilityYes.setSelected(false);
        } else {
            checkAvailabilityNo.setSelected(false);
        }

        // adding a product
        Car car = fleetDirectory.addCar();

        // setting the values
        car.setModelNumber(modelNumber);
        car.setSerialNumber(serialNumber);
        car.setmanufactureType(manufactureType);
        car.setManufacturedYear(Integer.parseInt(manufacturedYear));
        car.setAvailableSeats(Integer.parseInt(maxSeats));
        car.setCity(city);
//        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
//        LocalDateTime now = LocalDateTime.now();
//        car.setLastUpdatedDate(new Date(dtf.format(now)));
        if (checkAvailabilityNo.isSelected()) {

            car.setavailabilityStatus(false);
            checkAvailabilityYes.setSelected(false);
        } else {

            car.setavailabilityStatus(true);
            checkAvailabilityNo.setSelected(false);

        }

        if (checkExpCertNo.isSelected()) {
            car.setmaintenceCertificateExpiryStatus(false);

        } else {
            car.setmaintenceCertificateExpiryStatus(true);

        }

        // showing the message
        JOptionPane.showMessageDialog(null, "Created Successfully");

        // clearing the texts
        txtmanufactureType.setText("");
        txtCity.setText("");
        txtManufacturedYear.setText("");
        txtModelNumber.setText("");

        txtAvailableSeats.setText("");
        txtSerialNumber.setText("");
        checkAvailabilityNo.setSelected(false);
        checkAvailabilityYes.setSelected(false);
        checkExpCertNo.setSelected(false);
        checkExpCertYes.setSelected(false);
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();


    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void checkAvailabilityYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAvailabilityYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkAvailabilityYesActionPerformed

    private void checkAvailabilityNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAvailabilityNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkAvailabilityNoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox checkAvailabilityNo;
    private javax.swing.JCheckBox checkAvailabilityYes;
    private javax.swing.JCheckBox checkExpCertNo;
    private javax.swing.JCheckBox checkExpCertYes;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtAvailableSeats;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtManufacturedYear;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtSerialNumber;
    private javax.swing.JTextField txtmanufactureType;
    // End of variables declaration//GEN-END:variables
}
